#Policy and profile creation
resource "aws_iam_instance_profile" "handoff_profile" {
  name = "handoff_profile"
  role = "${aws_iam_role.handoff_role.name}"
}
resource "aws_iam_role" "handoff_role" {
  name = "handoff_role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
resource "aws_iam_policy_attachment" "handoff_policy" {
  name = "handoff_policy"
  roles = ["${aws_iam_role.handoff_role.name}"]
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
}

#We also, optionally, would like to enable a host to read it's own tags
# But, you will probably want to generalize this to your environment
## Adapted from code generated by:
##  https://awspolicygen.s3.amazonaws.com/policygen.html
## I really wish that we could use resource set to the exact ec2 instance(s) we want, but that fails
data "aws_iam_policy_document" "handoff_tags_policy" {
  statement {
    sid = "Stmt1557408958537"
    actions = [
      "ec2:DescribeTags",
    ]
    resources = [
      "*"
    ]
  }
}
resource "aws_iam_policy" "handoff_tags_policy" {
  name = "handoff_tags_policy"
  description = "Allow the handoff system to read it's own tags"

  policy = "${data.aws_iam_policy_document.handoff_tags_policy.json}"
}
resource "aws_iam_policy_attachment" "hadoff_tags_policy" {
  name = "handoff_tags_policy"
  roles = ["${aws_iam_role.handoff_role.name}"]
  policy_arn = "${aws_iam_policy.handoff_tags_policy.arn}"
}
